### PR TITLE
B19

### PR DESCRIPTION
**Pull request by BenWXY**

### CODE REVIEW

**Comment by zhuyuezx** [comment]
Great job, Ben!

**Comment by BenWXY** [comment]
Two points have not been implemented. Need to be fixed later on.

**Comment by wisechua** [comment]
I will follow up on the GUI and the interface for reading card

**Comment by Ez4Allen** [comment]
I will write tests for your code

**Comment by zhumengzhiren** [comment]
This fix is very good. I will write the description of this structure later.

**Comment by ElizaZoldyck** [comment]
Great job, good work team

**Pull request merged**
